# All of these options are unstable at the time of writing, so they don't really have any effect yet
format_code_in_doc_comments = true
format_strings = true
group_imports = "StdExternalCrate"
hex_literal_case = "Upper"
imports_granularity = "Module"
reorder_impl_items = true
wrap_comments = true
