[package]
name = "vscode-fuzzy-score-rs"
version = "0.2.8"
authors = ["Andrii Semkiv <semkiv@gmail.com>"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.14.0"
log = "0.4.26"
ndarray = "0.16.1"
